@baseUri=http://127.0.0.1:3000/api 

### insert artwork
POST {{baseUri}}/artwork-create
Content-Type: application/json

{
    "name": "Self-Portrait",
    "image": "https://arttoo.s3.us-west-1.amazonaws.com/photo_2024-04-06+17.28.19.jpeg",
    "image_width": 100,
    "image_height": 160,
    "description": "1/1 NFT from original oil painting\n\nOil paint, oil stick and charcoal on canvas\n\n09/2023 Barcelona, Spain\n\n100 x 160 cm (40‘ x 63’)",
    "token": 1000,
    "author": "Picasso",
    "author_avatar": "https://via.placeholder.com/150",
    "longitude": 51.53030424679481,
    "latitude": -0.07532395581990654,
    "address": "Exhibited digitally 01/2024 in Barcelona and 02/2024 at NFT Factory in Paris.",
    "location": "Shoreditch Exchange"
}

### get all artworks
GET {{baseUri}}/artworks-all
Content-Type: application/json

### get artwork by id
POST  {{baseUri}}/artwork-get
Content-Type: application/json

{
    "id": 2
}


### update artwork by id
PUT {{baseUri}}/artwork-update
Content-Type: application/json

{
    "name": "Artwork 2222",
    "image": "https://via.placeholder.com/150",
    "image_width": 150,
    "image_height": 150,
    "description": "Description 2",
    "token": 1,
    "author": "Author 2",
    "author_avatar": "https://via.placeholder.com/150",
    "id": 2
}

### delete artwork by id
DELETE {{baseUri}}/artwork-delete
Content-Type: application/json

{
    "id": 1
}
