@baseUri=http://127.0.0.1:3000/api 

### submit claim
POST {{baseUri}}/claim-submit
Content-Type: application/json

{
  "wallet_address": "walle",
  "wallet_type": "metamask",
  "artwork_id": 46
}


### reward get
GET {{baseUri}}/reward-get
Content-Type: application/json

{
  "artworkId": 4,
  "walletAddress": "0x4541F235bDe36CDb4cBa009Bdf1451614D1c5777"
}

### reward list
GET {{baseUri}}/reward-list
Content-Type: application/json

{
  "walletAddress": "0x4541F235bDe36CDb4cBa009Bdf1451614D1c5777"
}