@baseUri=http://127.0.0.1:3000/api 

### insert artwork
POST {{baseUri}}/user-create
Content-Type: application/json

{
  "wallet_address": "0x62a412068aBb2F85590EE8986c7F80eDFa1F4439",
  "wallet_type": "metamask"
}

### get users
GET {{baseUri}}/users-get
Content-Type: application/json


### transfer
GET {{baseUri}}/transfer
Content-Type: application/json


### transfer
POST https://arttoo.xyz/api/transfer
Content-Type: application/json

{
  "toWallet": "0x62a412068aBb2F85590EE8986c7F80eDFa1F4439",
  "amount": 1
}


### transfer
POST https://arttoo.xyz/api/transfer-test
Content-Type: application/json

{
  "toWallet": "0x62a412068aBb2F85590EE8986c7F80eDFa1F4439",
  "amount": 1
}
